import { index, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { users } from "./users.js";

/**
 * A single-use, 300-second-lived capability generated by its owner to
 * let one specific recipient establish a friendship with them --
 * never an authentication credential (see
 * docs/security/Social.md#blue-moon-token). Only the hash is stored,
 * same reasoning as `refresh_tokens.token_hash`: this is a lookup key
 * being redeemed, not a password being brute-forced offline.
 */
export const blueMoonTokens = pgTable(
  "blue_moon_tokens",
  {
    id: uuid("id").primaryKey(),
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    consumedByUserId: uuid("consumed_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("blue_moon_tokens_owner_id_idx").on(table.ownerId)],
);
